#!/usr/bin/usr bash

# Check if number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract arguments
path_to_file="$1"
ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$ip":~/ || { echo "Failed to transfer file."; exit 1; }

echo "File successfully transferred to $username@$ip:~/"

