#!/usr/bin/env bash
#This script displays Highlander

# print I am invincible!!! when receiving a SIGTERM signal
trap "echo I am invincible!!!" SIGTERM

while true;do
  echo "To infinity and beyond"
  sleep 2
done;
